<b>19BTRCR007 <br>
Myil Vaughanan V L

<b><h1> LAB PROGRAM 7: </h1></b> <br>
Write and run a program:<br> 
a. To find the addition of two matrices<br>
b. To find the product of two matrices<br>
c. To find the transpose of a matrix

In [2]:
import numpy as np

In [14]:
#a Addition of two matrices

#using array
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("ndarray A:\n",a)
print("ndarray B:\n",b)
print ("Addition of two ndarray: ")
print (np.add(a,b)) # we can also use a+b


ndarray A:
 [[1 2]
 [3 4]]
ndarray B:
 [[5 6]
 [7 8]]
Addition of two ndarray: 
[[ 6  8]
 [10 12]]


In [15]:
#using matrix
a=np.matrix(((1,2),(3,4)))
b=np.matrix(((5,6),(7,8)))
print("Matrix A:\n",a)
print("Matrix B:\n",b)
print ("Addition of two matrices: ")
print (np.add(a,b))

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Addition of two matrices: 
[[ 6  8]
 [10 12]]


In [7]:
#b Hadammard Multiplication

#using array
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("ndarray A:\n",a)
print("ndarray B:\n",b)
print ("Hadammard Multiplication of two ndarrays: ")
print (np.multiply(a,b))

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Hadammard Multiplication of two matrices: 
[[ 5 12]
 [21 32]]


In [16]:
#using matrix
a=np.matrix(((1,2),(3,4)))
b=np.matrix(((5,6),(7,8)))
print("Matrix A:\n",a)
print("Matrix B:\n",b)
print ("Hadammard Multiplication of two matrices: ")
print (np.multiply(a,b))

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Hadammard Multiplication of two matrices: 
[[ 5 12]
 [21 32]]


In [21]:
#b Normal Dot product

#using arrays
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("ndarray A:\n",a)
print("ndarray B:\n",b)
print ("Multiplication of two ndarrays: ")
print (np.dot(a,b))

ndarray A:
 [[1 2]
 [3 4]]
ndarray B:
 [[5 6]
 [7 8]]
Multiplication of two ndarrays: 
[[19 22]
 [43 50]]


In [18]:
#using matrix
a=np.matrix(((1,2),(3,4)))
b=np.matrix(((5,6),(7,8)))
print("Matrix A:\n",a)
print("Matrix B:\n",b)
print ("Multiplication of two matrices: ")
print (np.dot(a,b))

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Multiplication of two matrices: 
[[19 22]
 [43 50]]


In [19]:
#c Transpose of the matrix

#using arrays
a=np.array([[1,2],[3,4]])
print("Given ndarray is:\n",a)
print("Transpose of the given ndarray is:\n",a.T)

Given ndarray is:
 [[1 2]
 [3 4]]
Transpose of the given ndarray is:
 [[1 3]
 [2 4]]


In [20]:
#using matrices
a=np.matrix(((1,2),(3,4)))
print("Given matrix is:\n",a)
print("Transpose of the given matrix is:\n",a.T)

Given matrix is:
 [[1 2]
 [3 4]]
Transpose of the given matrix is:
 [[1 3]
 [2 4]]
