<h3>General syntax of creating numpy array:</h3>
numpy.array(object, dtype = None, copy = True, order = None, ndmin = 0)
<br>

<h3>Definitions:</h3>
object: Any object exposing the array interface method returns an array or any (nested) sequence.<br>
dtype: Desired data type of array, optional<br>
copy: Optional. By default (true), the object is copied<br>
order: C (row major as in C) or F (column major as in matlab) or A (any) (default)
<br>ndmin: Specifies minimum dimensions of resultant array

In [22]:
import numpy as np

In [23]:
a = np.array([10, 20, 30, 40, 50, 60])
print(a)
print(type(a))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
#To create an array filled with 0’s:  
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [26]:
#To create an array filled with 1’s:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [27]:
#To create an array with a range of elements:
print(np.arange(4))

[0 1 2 3]


In [28]:
#To create an array that contains a range of evenly spaced intervals. 
#To do this, you will specify the first number, last number, and the step size.
print(np.arange(5,30,5))

[ 5 10 15 20 25]


In [29]:
#to create an array with values that are spaced linearly in a specified interval
np.linspace(20, 100, num=10)

array([ 20.        ,  28.88888889,  37.77777778,  46.66666667,
        55.55555556,  64.44444444,  73.33333333,  82.22222222,
        91.11111111, 100.        ])

In [30]:
#Specifying your data type
#By default data type is floating point (np.float64),
#We can explicitly specify which data type we want using the dtype keyword.
x=np.ones(5)
print(x.dtype)

float64


In [31]:
x=np.ones(5,dtype=np.int64)
print(x.dtype)

int64


In [32]:
#ndarray.ndim will tell you the number of axes, or dimensions, of the array.

#ndarray.size will tell you the total number of elements of the array.
#This is the product of the elements of the array’s shape.

#ndarray.shape will display a tuple of integers that indicate the number of 
#elements stored along each dimension of the array. If, for example, 
#you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [33]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.ndim)
print(x.size)
print(x.shape)

[[1 2]
 [3 4]]
2
4
(2, 2)


<h3>Indexing and slicing

In [34]:
#You can index and slice NumPy arrays in the same ways you can slice Python lists.
a = np.array([5,6,7,8,9,10])
print(a)

[ 5  6  7  8  9 10]


In [35]:
print(a[0],a[3])

5 8


In [36]:
#Reversing the numpy array
print(a[::-1])

[10  9  8  7  6  5]


In [37]:
#Accessing the last element
print(a[-1])

10


In [38]:
print(a[-2:])
print(a[-4:-1])


[ 9 10]
[7 8 9]


In [39]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
print(a[a<8])
print(a[a>8])

[1 2 3 4 5 6 7]
[ 9 10 11 12]


In [41]:
a1 = a[(a > 2) & (a < 11)]
print(a1)

[ 3  4  5  6  7  8  9 10]


<h3>Basic Operations

In [42]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
#To find the sum of all the elements
print(np.sum(x))

36


In [44]:
#For axis=0, this means that we apply a function along each “column”, or all values that occur vertically.

#For axis=1, this means that we apply a function along each “row”, or all values horizontally.

x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [45]:
#To find the sum of elements columnwise
print(np.sum(x,axis=0))

[ 6  8 10 12]


In [46]:
#To find the sum of elements rowwise
print(np.sum(x,axis=1))

[10 26]


In [47]:
print(np.mean(x, axis=0)) 

[3. 4. 5. 6.]


In [48]:
print(np.mean(x, axis=1))

[2.5 6.5]


In [49]:
print(np.mean(x))

4.5


<h3>Sorting numpy array elements

In [50]:
a=np.array([10,5,6,8,2])
s=np.sort(a)
print(s)

[ 2  5  6  8 10]


In [51]:
#In Numpy, the np.sort() function does not allow us to sort an array in 
#descending order. Instead, we can reverse an array utilizing list slicing in 
#Python, after it has been sorted in ascending order(By default quicksort).
s1 = np.sort(a)
print(s1)

[ 2  5  6  8 10]


In [52]:
x1=np.array([10,-5,4,67,8])
print(x1)
x2=np.sort(x1)
print(x2)
x3=np.sort(x1)[::-1]
print(x3)

[10 -5  4 67  8]
[-5  4  8 10 67]
[67 10  8  4 -5]


In [53]:
s2 = s1[::-1]
print(s2)

[10  8  6  5  2]


In [55]:
#Concatenating numpy arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [56]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

x1=np.concatenate((x, y))
print(x1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [57]:
x1=np.concatenate((x, y),axis=0)
print(x1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [58]:
x2=np.concatenate((x, y),axis=1)
print(x2)

[[1 2 5 6]
 [3 4 7 8]]


In [59]:
#to compute min, max n on the ndarray
print(x)

print("Max value is: ", x.max())
print("Min value is: ", x.min())

[[1 2]
 [3 4]]
Max value is:  4
Min value is:  1


In [60]:
#to compute min, max n on the ndarray columnwise
print(x)

print("Max value is: ", x.max(axis=0))
print("Min value is: ", x.min(axis=0))

[[1 2]
 [3 4]]
Max value is:  [3 4]
Min value is:  [1 2]


In [61]:
#Reshaping is changing the arrangement of items so that shape of the array 
#changes while maintaining the same number of dimensions.
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [62]:
x1=x.reshape(4,3)
print(x1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [67]:
x2=x.reshape(2,6)
print(x2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [68]:
#flatten():It will convert a multi-dimensional array to a flat 1d array.
#And not any other shape.
#Changing the flattened array does not change parent array
list5=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a1=np.array(list5)
print(a1)
a3=a1.flatten()
print(a3)
a4=a3
print(a4)
a4[2]=100
print("Parent array is:")
print(a1)
print(a3)
print(a4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Parent array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[  1   2 100   4   5   6   7   8   9  10  11  12]
[  1   2 100   4   5   6   7   8   9  10  11  12]


In [69]:
#ravel():The new array created using ravel() method is a reference to the parent
#array. So, any changes to the new array will affect the parent as well.
#But is memory efficient since it does not create a copy.
print(a1)
a11=a1.ravel()
print(a11)
a12=a11
#print(a12)
a12[2]=1000
print(a12)
#print(a11)
print(a1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[   1    2 1000    4    5    6    7    8    9   10   11   12]
[[   1    2 1000    4]
 [   5    6    7    8]
 [   9   10   11   12]]


In [70]:
#Stacking: Several arrays can be stacked together along different axes
#np.vstack:To stack arrays along vertical axis
#np.hstack: To stack arrays along horizontal axis

x1=np.array([[1,2],[3,4]])
x2=np.array([[5,6],[7,8]])
print(x1)
print(x2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


np.vstack((x1,x2))

In [72]:
np.hstack((x1,x2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

<h3>Numpy Module provides different methods for matrix operations.

In [73]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [3, 4]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [74]:
#  add()is used to add matrices
print ("Addition of two matrices: ")
print (np.add(x,y))

Addition of two matrices: 
[[2 4]
 [6 8]]


In [76]:
#NumPy’s np.flip() function allows you to flip, or reverse, the contents of an 
#array along an axis. When using np.flip, specify the array you would like to 
#reverse and the axis. If you don’t specify the axis, NumPy will reverse the 
#contents along all of the axes of your input array.

a=np.array([1,2,3,4,5,6])
print(a)
print(np.flip(a,axis=0))

[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [77]:
#2D array
x=np.array([[1,2,3],[4,5,6]])
print(x)

#Column-wise flip
print(np.flip(x,axis=0))

#Row-wise flip
print(np.flip(x,axis=1))

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]]


In [78]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [79]:
#Hammard Multiplication

d=a*b
print(d)

[[ 1  4]
 [ 9 16]]


In [80]:
#Dot product

e=a.dot(b)
print(e)

[[ 7 10]
 [15 22]]


In [81]:
#A Simple excercise

import numpy as np
arr = np.array([[ 1,  2,  3,  4,  5],
                   [ 6,  7,  8,  9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25],
                   [26, 27, 28, 29, 30]])
print("\n Given array is:\n")
print(arr)

print("\n Odd rows of array is:\n")
for i in range(arr.shape[0]):
    if i %2 == 0:
        print(arr[i,:])
        
print("\n Even rows of array is:\n")
for i in range(arr.shape[0]):
    if i %2 != 0:
        print(arr[i,:])

print("\n Even Columns of array is:\n")
for i in range(arr.shape[1]):
    if i %2 == 1:
        print(arr[:,i])
        
        
print("\n Odd Columns of array is:\n")
for i in range(arr.shape[1]):
    if i %2 != 1:
        print(arr[:,i])


 Given array is:

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

 Odd rows of array is:

[1 2 3 4 5]
[11 12 13 14 15]
[21 22 23 24 25]

 Even rows of array is:

[ 6  7  8  9 10]
[16 17 18 19 20]
[26 27 28 29 30]

 Even Columns of array is:

[ 2  7 12 17 22 27]
[ 4  9 14 19 24 29]

 Odd Columns of array is:

[ 1  6 11 16 21 26]
[ 3  8 13 18 23 28]
[ 5 10 15 20 25 30]
