<h3>General syntax of creating numpy array:</h3>
numpy.array(object, dtype = None, copy = True, order = None, ndmin = 0)
<br>

<h3>Definitions:</h3>
object: Any object exposing the array interface method returns an array or any (nested) sequence.<br>
dtype: Desired data type of array, optional<br>
copy: Optional. By default (true), the object is copied<br>
order: C (row major as in C) or F (column major as in matlab) or A (any) (default)
<br>ndmin: Specifies minimum dimensions of resultant array

In [22]:
import numpy as np

In [23]:
a = np.array([10, 20, 30, 40, 50, 60])
print(a)
print(type(a))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
#To create an array filled with 0’s:  
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [26]:
#To create an array filled with 1’s:
print(np.ones(5))

[1. 1. 1. 1. 1.]


In [27]:
#To create an array with a range of elements:
print(np.arange(4))

[0 1 2 3]


In [28]:
#To create an array that contains a range of evenly spaced intervals. 
#To do this, you will specify the first number, last number, and the step size.
print(np.arange(5,30,5))

[ 5 10 15 20 25]


In [29]:
#to create an array with values that are spaced linearly in a specified interval
np.linspace(20, 100, num=10)

array([ 20.        ,  28.88888889,  37.77777778,  46.66666667,
        55.55555556,  64.44444444,  73.33333333,  82.22222222,
        91.11111111, 100.        ])

In [30]:
#Specifying your data type
#By default data type is floating point (np.float64),
#We can explicitly specify which data type we want using the dtype keyword.
x=np.ones(5)
print(x.dtype)

float64


In [31]:
x=np.ones(5,dtype=np.int64)
print(x.dtype)

int64


In [32]:
#ndarray.ndim will tell you the number of axes, or dimensions, of the array.

#ndarray.size will tell you the total number of elements of the array.
#This is the product of the elements of the array’s shape.

#ndarray.shape will display a tuple of integers that indicate the number of 
#elements stored along each dimension of the array. If, for example, 
#you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [33]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.ndim)
print(x.size)
print(x.shape)

[[1 2]
 [3 4]]
2
4
(2, 2)


<h3>Indexing and slicing

In [34]:
#You can index and slice NumPy arrays in the same ways you can slice Python lists.
a = np.array([5,6,7,8,9,10])
print(a)

[ 5  6  7  8  9 10]


In [35]:
print(a[0],a[3])

5 8


In [36]:
#Reversing the numpy array
print(a[::-1])

[10  9  8  7  6  5]


In [37]:
#Accessing the last element
print(a[-1])

10


In [38]:
print(a[-2:])
print(a[-4:-1])


[ 9 10]
[7 8 9]


In [39]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
print(a[a<8])
print(a[a>8])

[1 2 3 4 5 6 7]
[ 9 10 11 12]


In [41]:
a1 = a[(a > 2) & (a < 11)]
print(a1)

[ 3  4  5  6  7  8  9 10]


<h3>Basic Operations

In [42]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
#To find the sum of all the elements
print(np.sum(x))

36


In [44]:
#For axis=0, this means that we apply a function along each “column”, or all values that occur vertically.

#For axis=1, this means that we apply a function along each “row”, or all values horizontally.

x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [45]:
#To find the sum of elements columnwise
print(np.sum(x,axis=0))

[ 6  8 10 12]


In [46]:
#To find the sum of elements rowwise
print(np.sum(x,axis=1))

[10 26]


In [47]:
print(np.mean(x, axis=0)) 

[3. 4. 5. 6.]


In [48]:
print(np.mean(x, axis=1))

[2.5 6.5]


In [49]:
print(np.mean(x))

4.5
